title: Blog
author: Herbert Ilhan Tanujaya
email: h.i@u.nus.edu
description: >
  Posts on things that interest me, such as Computer Science,
  building software, and Mathematics.
url: "blog.herbert.id"
abouturl: "herbert.id"

# Build settings
markdown: kramdown
collections:
  - experience
  - projects
gems:
  - jekyll-feed
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
