title: Blog
author: Herbert Ilhan Tanujaya

# Build settings
markdown: kramdown
collections:
  - experience
  - projects
plugins:
  - jekyll-feed
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
permalink: :year/:month/:title/
